# Generated by Django 2.2.5 on 2021-05-20 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NCRMgmntSystem', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.AlterModelOptions(
            name='ncradvusertbl',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='ncrdetailmstr',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'managed': False},
        ),
    ]
